In [1]:
import sqlite3
import pandas as pd

# built into Python
# for readable output

con = sqlite3.connect(r'..\data\raw\airtel.db') # two dots: notebooks/

def q(sql):
    return pd.read_sql(sql, con)

# the same helper as
# the IPL project

In [2]:
q("""
SELECT name
FROM sqlite_master
WHERE type = 'table'
ORDER BY name;
""")

          name
0      circles
1   complaints
2    customers
3        plans
4    recharges
5  usage_daily

In [3]:
q("""
SELECT 'circles' AS tbl, COUNT(*) AS n FROM circles
UNION ALL
SELECT 'plans', COUNT(*) FROM plans
UNION ALL
SELECT 'customers', COUNT(*) FROM customers
UNION ALL
SELECT 'usage_daily', COUNT(*) FROM usage_daily
UNION ALL
SELECT 'recharges', COUNT(*) FROM recharges
UNION ALL
SELECT 'complaints', COUNT(*) FROM complaints
ORDER BY tbl;
""")

           tbl        n
0      circles       22
1   complaints    26841
2    customers    22000
3        plans       14
4    recharges   408089
5  usage_daily  1326739